### ISSUE TITLE
Stops calculating after 1000km

### ISSUE THREAD

**Issue by Reilapon** [EdFage/fuelCostCalculator#14]
I'm trying to plot a road trip, and apparently it stops calculating when the distance is past 1000km. 999km works fine.

**Comment by EdFage** [comment]
Hey, sorry for the slow reply on this, I am travelling. I'll take a look when I get the change. Thanks for submitting the issue!

Ed

**Comment by EdFage** [comment]
Hey @Reilapon, this should now be fixed in the [latest version](https://github.com/EdFage/fuelCostCalculator/releases/tag/v0.1.4).

If you download the extension directly from GitHub then you can get the latest version right away, otherwise it should be updated on the Chrome Store in a few days.

Thank you for opening this issues and apologies that it took a while to resolve!

**Comment by Reilapon** [comment]
Thank you, and no worries!
